name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v**']

permissions:
  contents: read

jobs:
  lint:
    name: Test and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - name: Fetch restaurant URLs (limited)
        run: npm run start -- fetch-urls --max-pages 1
      - name: Fetch restaurant details (limited)
        run: npm run start -- fetch-details --concurrency 1
      - name: Upload data/restaurants.json as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: restaurants.json
          path: data/restaurants.json
          if-no-files-found: error