name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v**']

permissions:
  contents: read

jobs:
  lint:
    name: Test and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.0
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - name: Perform limited run of script
        run: npm run start -- --limit 1
      - name: Upload data/restaurants.json as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: restaurants.json
          path: data/restaurants.json
          if-no-files-found: error